### ISSUE TITLE
The result of unit test 'test_timer_leak_nocancel' and 'test_timer_leak_nocancel' is nondeterministic.

### ISSUE THREAD

**Issue by Suckzoo** [achimnol/aiotools#8]
It seems there is an issue related with common concurrency problem (e.g. deadlock?)
Mostly it succeeds, but it fails sometimes on local development environment in two ways:
- On `test_timer_leak_nocancel`, it returns wrong result in this line
```python
       assert spawn_count == done_count # e.g. 9 == 8
```
- On `test_timer_cancel`, it does not halt sometimes.

**Comment by achimnol** [comment]
Now it's resolved using v1.0's [`timer.VirtualClock`](https://aiotools.readthedocs.io/en/latest/aiotools.timer.html#aiotools.timer.VirtualClock) applied to the test suite.
